### ISSUE TITLE
Please provide SMP support

### ISSUE THREAD

**Issue by rapgro** [rlaager/docsis#7]
Cause of the lexer there's no support for parallel builds.

**Comment by rlaager** [comment]
Patches are welcome, but I'm not going to write this. Also, it's not like this is a huge program to build.

**Comment by rlaager** [comment]
make -j2 doesn't fail. What exactly are you seeing as the problem anyway?

**Comment by rapgro** [comment]
Try with more than just two jobs. My Fedora uses four at least: make %{?_smp_mflags}

$ rpm -E %{?_smp_mflags}
-j4

**Comment by rlaager** [comment]
It works for me with -j4. But again, this entire application takes like 2 seconds to build. Worst case, you can just build with `make -j1`. I'm not really doing a lot of maintenance on this program. I just took over because it was completely abandoned. So I've basically been only accepting patches as they come in.
